<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */
 
 class eventclass_tbl_distributivo_proyectos  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["BeforeAdd"]=true;


	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before record added
function BeforeAdd(&$values, &$message, $inline, &$pageObject)
{

		$values['hrs_docente_tutor'] = $values['hrs_docente_tutor']!="" ? $values['hrs_docente_tutor']: 0;
$values['hrs_docente_participante'] = $values['hrs_docente_participante']!="" ? $values['hrs_docente_participante']: 0;
$values['hrs_seguimiento_graduados'] = $values['hrs_seguimiento_graduados']!="" ? $values['hrs_seguimiento_graduados']: 0;
$values['hrs_supervision_pasantias_comunitario'] = $values['hrs_supervision_pasantias_comunitario']!="" ? $values['hrs_supervision_pasantias_comunitario']: 0;

$sql = "INSERT INTO tbl_distributivo_proyectos(cedula, hrs_proyecto_vinculacion, hrs_docente_tutor, hrs_docente_participante, hrs_seguimiento_graduados, hrs_supervision_pasantias_comunitario, id_carrera, id_periodo)
values ('".$values['cedula']."',".$values['hrs_proyecto_vinculacion'].", ".$values['hrs_docente_tutor'].", ".$values['hrs_docente_participante'].", ".$values['hrs_seguimiento_graduados'].", ".$values['hrs_supervision_pasantias_comunitario'].", ".$values['id_carrera'].", ".$values['id_periodo']." );";
CustomQuery($sql);

$pageObject->setMessageType(MESSAGE_SUCCESS);

$pageObject->setMessage("Docente Guardada Correctamente");

// Place event code here.
// Use "Add Action" button to add code snippets.

return false;
;		
} // function BeforeAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>
