<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */
 
 class eventclass_tbl_extension  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["BeforeAdd"]=true;


	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before record added
function BeforeAdd(&$values, &$message, $inline, &$pageObject)
{

		$values['extension']=strtoupper($values['extension']);

// Place event code here.
// Use "Add Action" button to add code snippets.


//**********  Insert a record into another table  ************

$sql = "INSERT INTO tbl_extension (extension, id_ciudad, codigo_u) values ('".$values['extension']."',".$values['id_ciudad'].",'".$values['codigo_u']."')";
CustomQuery($sql);

$pageObject->setMessageType(MESSAGE_SUCCESS);

$pageObject->setMessage("Extensión Guardada Correctamente");


return false;
;		
} // function BeforeAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>
